// <auto-generated />
using ApiWithSQLConnection.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiWithSQLConnection.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240112161318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Decade", b =>
                {
                    b.Property<int>("DecadeValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("DecadeValue");

                    b.ToTable("Decades");

                    b.HasData(
                        new
                        {
                            DecadeValue = 1960
                        },
                        new
                        {
                            DecadeValue = 1970
                        },
                        new
                        {
                            DecadeValue = 1980
                        },
                        new
                        {
                            DecadeValue = 1990
                        },
                        new
                        {
                            DecadeValue = 2000
                        },
                        new
                        {
                            DecadeValue = 2010
                        },
                        new
                        {
                            DecadeValue = 2020
                        });
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.GovPolicy_Decade", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Decade")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PolicyID");

                    b.ToTable("GovPolicy_Decades");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.GovernmentPolicy_Performance", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PolicyID");

                    b.ToTable("GovernmentPolicy_Performances");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Government_Policy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LinkExtractedText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PolicyID");

                    b.ToTable("Government_Policies");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Neighborhood", b =>
                {
                    b.Property<int>("NeighborhoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NeighborhoodID");

                    b.ToTable("Neighborhoods");

                    b.HasData(
                        new
                        {
                            NeighborhoodID = 1,
                            Name = "Belém"
                        },
                        new
                        {
                            NeighborhoodID = 2,
                            Name = "Alcântara"
                        },
                        new
                        {
                            NeighborhoodID = 3,
                            Name = "Baixa"
                        },
                        new
                        {
                            NeighborhoodID = 4,
                            Name = "Benfica"
                        },
                        new
                        {
                            NeighborhoodID = 5,
                            Name = "Laranjeiras"
                        },
                        new
                        {
                            NeighborhoodID = 6,
                            Name = "Alameda"
                        },
                        new
                        {
                            NeighborhoodID = 7,
                            Name = "Penha De França"
                        },
                        new
                        {
                            NeighborhoodID = 8,
                            Name = "Lumiar"
                        },
                        new
                        {
                            NeighborhoodID = 9,
                            Name = "Alvalade"
                        },
                        new
                        {
                            NeighborhoodID = 10,
                            Name = "Olivais"
                        },
                        new
                        {
                            NeighborhoodID = 11,
                            Name = "Parque Das Nações"
                        });
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Price", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Decade")
                        .HasColumnType("int");

                    b.Property<string>("LinkExtractedText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PropertyID");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LinkExtractedText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("PropertyID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.PropertyPricePer_Decade", b =>
                {
                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<string>("Decade")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PropertyID", "Decade");

                    b.ToTable("PropertyPricePer_Decades");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.PublicSentiment", b =>
                {
                    b.Property<int>("SentimentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkExtractedText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SentimentID");

                    b.ToTable("PublicSentiments");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.PublicSentiment_Decade", b =>
                {
                    b.Property<int>("SentimentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Decade")
                        .HasColumnType("int");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SentimentID");

                    b.ToTable("PublicSentiment_Decades");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.PublicSentiment_Neighborhood", b =>
                {
                    b.Property<int>("SentimentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NeighborhoodID")
                        .HasColumnType("int");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SentimentID");

                    b.ToTable("PublicSentiment_Neighborhoods");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RegionID");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionID = 1,
                            Name = "Lisboa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
