// <auto-generated />
using System;
using ApiWithSQLConnection.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiWithSQLConnection.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Course", b =>
                {
                    b.Property<int>("Cour_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cour_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Cour_id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("ApiWithSQLConnection.Models.Database.Student", b =>
                {
                    b.Property<int>("Stu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseCour_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Stu_bdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Stu_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stu_gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stu_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stu_place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Stu_id");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
